# Generated by Django 4.1.2 on 2023-03-11 21:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionsApp', '0009_alter_questiongroupmodel_online_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('StudentPerformance_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Completed_At', models.DateTimeField(default=datetime.datetime(2023, 3, 11, 21, 21, 26, 495827, tzinfo=datetime.timezone.utc))),
                ('Question_Information', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questiongroupmodel')),
                ('Student_Information', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
