# Generated by Django 4.1.2 on 2023-03-11 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0009_alter_questiongroupmodel_online_status'),
        ('StudentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='Question_Group_Information',
            field=models.ForeignKey(default=uuid.UUID('0047e290-5146-4773-80f3-4bfa84ab5462'), on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questiongroupmodel'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='Completed_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 22, 16, 4, 647028, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='Question_Information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questionsmodel'),
        ),
    ]
