# Generated by Django 4.1.2 on 2023-03-22 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0010_alter_questionsmodel_question_text'),
        ('StudentsApp', '0004_alter_studentperformance_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='Completed_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='Question_Group_Information',
            field=models.ForeignKey(default=uuid.UUID('aba52ffa-a20e-4b0b-86a1-17f5c7cad623'), on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questiongroupmodel'),
        ),
    ]
