# Generated by Django 4.1.2 on 2023-04-18 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0010_alter_questionsmodel_question_text'),
        ('StudentsApp', '0007_remove_studentperformance_question_group_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='Question_Group_Information',
            field=models.ForeignKey(default=uuid.UUID('08bf213c-f23b-4b95-a34c-ab9619010f92'), on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questiongroupmodel'),
        ),
    ]
