# Generated by Django 4.1.2 on 2023-04-19 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0011_alter_questionsmodel_image_for_question'),
        ('StudentsApp', '0009_remove_studentperformance_question_group_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='Question_Group_Information',
            field=models.ForeignKey(default=uuid.UUID('309d68fa-a464-4d03-a5ee-79f567271144'), on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questiongroupmodel'),
        ),
    ]
