# Generated by Django 4.1.2 on 2023-05-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0014_questiongroupmodel_is_demarcate'),
        ('StudentsApp', '0010_studentperformance_question_group_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentperformance',
            name='Question_Group_Information',
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='Question_Information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsApp.questionsmodel'),
        ),
    ]
