# Generated by Django 4.1.2 on 2023-05-16 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0014_questiongroupmodel_is_demarcate'),
        ('StudentsApp', '0012_studentperformance_question_group_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='Question_Group_Information',
            field=models.ForeignKey(default=uuid.UUID('55e6410e-46e8-4cb0-8a3e-5a221582cd2a'), on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questiongroupmodel'),
        ),
    ]
