# Generated by Django 4.1.2 on 2023-05-25 13:40

import StudentsApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0014_questiongroupmodel_is_demarcate'),
        ('StudentsApp', '0013_alter_studentperformance_question_group_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='Question_Group_Information',
            field=models.ForeignKey(default=StudentsApp.models.StudentPerformance.get_default_question_group_id, on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questiongroupmodel'),
        ),
    ]
