# Generated by Django 4.1.2 on 2023-05-30 16:14

import StudentsApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0014_questiongroupmodel_is_demarcate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudentsApp', '0014_alter_studentperformance_question_group_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='Question_Group_Information',
            field=models.ForeignKey(default=StudentsApp.models.StudentPerformance.get_default_question_group_id, on_delete=django.db.models.deletion.CASCADE, to='QuestionsApp.questiongroupmodel'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='Student_Information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
