# Generated by Django 4.1.2 on 2023-07-10 06:31

import StudentsApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0016_alter_questiongroupmodel_creators_information'),
        ('DemarcateApp', '0005_alter_demarcatequestionsmodel_group_name_of_quesitons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudentsApp', '0015_alter_studentperformance_question_group_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerfomranceInDemarcateQuizes',
            fields=[
                ('StudentPerformance_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Score_Per_Question', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Completed_At', models.DateTimeField(auto_now_add=True)),
                ('Question_Group_Information', models.ForeignKey(default=StudentsApp.models.StudentPerfomranceInDemarcateQuizes.get_default_question_group_id, on_delete=django.db.models.deletion.CASCADE, to='QuestionsApp.questiongroupmodel')),
                ('Question_Information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemarcateApp.demarcatequestionsmodel')),
                ('Student_Information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
