# Generated by Django 4.1.2 on 2023-03-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0002_create_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='Full_Name',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='Accept_Terms_of_Services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='Receive_News',
            field=models.BooleanField(default=False),
        ),
    ]
