# Generated by Django 4.1.2 on 2023-03-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0003_remove_customusermodel_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='Mobile_Number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
