# Generated by Django 4.1.2 on 2023-02-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='Path_To_Folder',
        ),
    ]
