# Generated by Django 4.1.2 on 2023-03-07 22:17

import ImagesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0004_Create_ImageGroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='Image_Number',
            field=models.IntegerField(default=ImagesApp.models.ImageModel.number, unique=True),
        ),
    ]
