# Generated by Django 4.1.2 on 2023-05-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0005_imagemodel_image_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='Image_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.imagegroupmodel', verbose_name='Group To Which This Image Belongs To'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='Type_Of_Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.imagetypemodel'),
        ),
        migrations.AlterField(
            model_name='imagesquestionsmodel',
            name='Id_Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.imagemodel'),
        ),
    ]
