# Generated by Django 4.1.2 on 2023-06-01 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesModel',
            fields=[
                ('IDCase', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('CaseStudyNumber', models.IntegerField()),
                ('CaseStudyFileName', models.CharField(max_length=500)),
                ('CaseStudyFile', models.FileField(upload_to='pdf_files/')),
            ],
        ),
    ]
