# Generated by Django 4.1.2 on 2023-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0003_alter_questionsmodel_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroupmodel',
            name='Date_Of_Creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
