# Generated by Django 4.1.2 on 2023-03-07 12:02

import QuestionsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0004_alter_questiongroupmodel_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroupmodel',
            name='Group_Number',
            field=models.IntegerField(default=QuestionsApp.models.QuestionGroupModel.number, unique=True),
        ),
    ]
