# Generated by Django 4.1.2 on 2023-03-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0006_alter_questionsmodel_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsmodel',
            old_name='Image_For_Quesiton',
            new_name='Image_For_Question',
        ),
        migrations.RenameField(
            model_name='questionsmodel',
            old_name='Video_For_Quesiton',
            new_name='Video_For_Question',
        ),
    ]
