# Generated by Django 4.1.2 on 2023-03-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0007_rename_image_for_quesiton_questionsmodel_image_for_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='Correct_Answer',
        ),
        migrations.AddField(
            model_name='mcqmodel',
            name='Is_Right',
            field=models.BooleanField(default=False),
        ),
    ]
