# Generated by Django 4.1.2 on 2023-03-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0008_remove_questionsmodel_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroupmodel',
            name='Online_Status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
