# Generated by Django 4.1.2 on 2023-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0009_alter_questiongroupmodel_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='Question_Text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
