# Generated by Django 4.1.2 on 2023-04-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0005_imagemodel_image_number'),
        ('QuestionsApp', '0011_alter_questionsmodel_image_for_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='Image_For_Question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ImagesApp.imagemodel', verbose_name='Link Image'),
        ),
    ]
