# Generated by Django 4.1.2 on 2023-05-30 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionsApp', '0015_alter_questionsmodel_group_name_of_quesitons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroupmodel',
            name='Creators_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
