# Generated by Django 4.1.2 on 2023-02-22 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('Id_Video', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Description_Of_Video', models.CharField(max_length=1000)),
                ('Video_File', models.FileField(upload_to='videos/')),
                ('Date_Of_Upload', models.DateField(blank=True, null=True)),
                ('Creators_Information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
