# Generated by Django 4.1.2 on 2023-04-03 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ImagesApp', '0005_imagemodel_image_number'),
        ('QuestionsApp', '0010_alter_questionsmodel_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemarcateQuestion',
            fields=[
                ('Id_Marked', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('StartX', models.IntegerField(blank=True, null=True)),
                ('StartY', models.IntegerField(blank=True, null=True)),
                ('Width', models.IntegerField(blank=True, null=True)),
                ('Height', models.IntegerField(blank=True, null=True)),
                ('Area', models.IntegerField(blank=True, null=True)),
                ('Question_Image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ImagesApp.imagemodel', verbose_name='Link Image')),
                ('Related_Question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionsApp.questionsmodel', verbose_name='Related Question')),
            ],
        ),
    ]
