# Generated by Django 4.1.2 on 2023-05-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsApp', '0016_alter_questiongroupmodel_creators_information'),
        ('DemarcateApp', '0004_remove_demarcatequestionsmodel_image_for_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demarcatequestionsmodel',
            name='Group_Name_Of_Quesitons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionsApp.questiongroupmodel', verbose_name='Group Name of Subject'),
        ),
    ]
